function [fitresult, gof] = createFit(t, V, W)
%CREATEFIT(T,V,W)
%  Create a fit.
%
%  Data for 'ENPH259 HW1 Part1' fit:
%      X Input : t
%      Y Output: V
%      Weights : W
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Sep-2013 12:07:47


%% Fit: 'ENPH259 HW1 Part1'.
[xData, yData, weights] = prepareCurveData( t, V, W );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf];
opts.StartPoint = [0.257508254123736 0.840717255983663 0.254282178971531];
opts.Upper = [Inf Inf Inf];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'ENPH259 HW1 Part1' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'V vs. t with W', 'ENPH259 HW1 Part1', 'Location', 'NorthEast' );
% Label axes
xlabel( 't' );
ylabel( 'V' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'ENPH259 HW1 Part1 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel( 't' );
ylabel( 'V' );
grid on


