[file_name, path_name] = uigetfile({...
'*.atf;*.abf', 'All Axon Files (*.atf. *.abf)';...
'*.atf','Axon Text Files (*.atf)';...
'*.abf','Axon Binary Files (*.abf)'}, 'Please select ENG data file');
handles.path_and_file = strcat(path_name, file_name);
guidata(hObject, handles);
set(handles.path_file_edit, 'String', handles.path_and_file);