img1 = imread('1.png');
img2 = imread('2.png');
img1 = im2bw(img1);
img2 = im2bw(img2);
oPos = img2 .* img1;
oNeg = imcomplement(img2) .* imcomplement(img1);
overlap = oPos + oNeg;
overlapN = imcomplement(overlap);
rec = imreconstruct(im2bw(overlapN), img2);
recN = imcomplement(rec);
fin = imreconstruct(recN, img2);
subplot(5, 2, 1), imshow(img2);
subplot(5, 2, 2), imshow(img1);
subplot(5, 2, 3), imshow(oPos);
subplot(5, 2, 4), imshow(oNeg);
subplot(5, 2, 5), imshow(overlap);
subplot(5, 2, 6), imshow(overlapN);
subplot(5, 2, 7), imshow(rec);
subplot(5, 2, 8), imshowpair(img2,img1);
subplot(5, 2, 9), imshow(recN);
subplot(5, 2, 10), imshow(fin);