function h = buildMtcontrolGui;

global gv;

nMarkers = gv.nMarkers;
bh = 0.095;
bw = 0.85 / nMarkers;
if bw > 0.15,
    bw = 0.15;
end

totalWidth = nMarkers*.05+0.2;
if totalWidth > 1,
    totalWidth = 1;
end
y = fliplr(linspace(0.05, 0.8, 7));

controlFigH = figure('Color',[0.8 0.8 0.8], ...
	'MenuBar', 'None', ...
	'Name', 'MT2D Marker Configurator', ...
	'NumberTitle', 'off', ...
    'Units', 'normalized',...
	'Position', [1-totalWidth 0.03 totalWidth 0.3]);

h.fig = controlFigH;

xMin = 0;

uicontrol( 'Parent', controlFigH, ...
    'Style', 'text', ...
	'Units','Normalized', ...
	'Position',[xMin y(1) .15 bh], ...
	'String', 'Marker', ...
    'FontWeight','n',...
    'FontUnits','points', ...
    'FontSize', 8);

uicontrol( 'Parent', controlFigH, ...
    'Style', 'text', ...
	'Units', 'Normalized', ...
	'Position', [xMin y(2) .15 bh], ...
    'String', 'Labels', ...
    'ToolTipString', 'Change text labels for marker',...
    'FontWeight', 'n',...
    'FontUnits', 'points', ...
    'FontSize', 8);

uicontrol( 'Parent', controlFigH, ...
    'Style', 'text', ...
	'Units', 'Normalized', ...
	'Position', [xMin y(3) .15 bh], ...
    'String', 'Enable', ...
    'ToolTipString', 'Check box if marker is to be tracked. Uncheck if marker is not to be tracked',...
    'FontWeight', 'n',...
    'FontUnits', 'points', ...
    'FontSize', 8);

uicontrol( 'Parent', controlFigH, ...
    'Style', 'text', ...
	'Units', 'Normalized', ...
	'Position', [xMin y(4) .15 bh], ...
    'String', 'Dark Color', ...
    'ToolTipString', 'Check box if markers are dark, uncheck if markers are light',...
    'FontWeight', 'n',...
    'FontUnits', 'points', ...
    'FontSize', 8);

uicontrol( 'Parent', controlFigH, ...
    'Style', 'text', ...
	'Units', 'Normalized', ...
	'Position', [xMin y(5) .15 bh], ...
    'String', sprintf('Size\n(pixels)'), ...
    'ToolTipString', 'Adjust size of search boxes for locating markers',...
    'FontWeight', 'n',...
    'FontUnits', 'points', ...
    'FontSize', 8);

uicontrol( 'Parent', controlFigH, ...
    'Style', 'text', ...
	'Units', 'Normalized', ...
	'Position', [xMin y(6) .15 bh], ...
    'String', sprintf('Size\nScalar'), ...
    'ToolTipString', 'Multiplier used to amplify size of search box for each marker. Fast moving markers should have a higher value.',...
    'FontWeight', 'n',...
    'FontUnits', 'points', ...
    'FontSize', 8);

uicontrol( 'Parent', controlFigH, ...
    'Style', 'text', ...
	'Units', 'Normalized', ...
	'Position', [xMin y(7) .15 bh], ...
    'String', sprintf('Error\nTolerance'), ...
    'ToolTipString', 'Tolerance value used for detecting errors in the tracking. INCREASE this number to make the program LESS sensitive to errors. DECREASE this value to make the program more sensitive',...
    'FontWeight', 'n',...
    'FontUnits', 'points', ...
    'FontSize', 8);


xMin = 0.15;

for i = 1:gv.nMarkers,
    uicontrol( 'Parent', controlFigH, ...
        'Style', 'text', ...
    	'Units', 'Normalized', ...
    	'Position', [xMin+(i-1)*bw, y(1), bw, bh], ...
        'String', i, ...
        'FontWeight', 'b',...
        'FontUnits', 'points', ...
        'FontSize', 8);
    
    if i < gv.nMarkers,
        h.mrkrLink(i) = uicontrol( 'Parent', controlFigH, ...
            'Style', 'check', ...
    	    'Units', 'Normalized', ...
    	    'Position', [xMin+i*bw, 0.89, bw/4, .06], ...
            'CallBack', 'mtControlGUI mrkrLink', ...
            'Value', gv.mrkrLink(i), ...
            'Max', 1, ...        
            'Min', 0, ...
            'FontWeight', 'n',...
            'FontUnits', 'points', ...
            'FontSize', 8);
    else,
        uicontrol( 'Parent', controlFigH, ...
            'Style', 'text', ...
    	    'Units', 'Normalized', ...
    	    'Position', [.15, .89, bw, .06], ...
            'String', 'Linked', ...
            'FontWeight', 'n',...
            'FontUnits', 'Points', ...
            'ToolTipString', 'Check box to link adjacent markers in the stick figure', ...
            'FontSize', 8);
        
    end
    
    h.mrkrLabels(i) = uicontrol( 'Parent', controlFigH, ...
        'Style', 'edit', ...
    	'Units', 'Normalized', ...
    	'Position', [xMin+(i-1)*bw, y(2), bw, bh], ...
        'String', gv.mrkrLabels{i}, ...
        'CallBack', 'mtControlGUI mrkrLabels', ...
        'FontWeight', 'b',...
        'FontUnits', 'points', ...
        'FontSize', 8);

    h.mrkrEnable(i) = uicontrol( 'Parent', controlFigH, ...
        'Style', 'check', ...
    	'Units', 'Normalized', ...
    	'Position', [xMin+(i-1)*bw, y(3), bw, bh], ...
        'CallBack', 'mtControlGUI mrkrEnable', ...
        'Value', gv.mrkrEnable(i), ...
        'Max', 1, ...        
        'Min', 0, ...
        'FontWeight', 'b',...
        'FontUnits', 'points', ...
        'FontSize', 8);
    
    h.mrkrInvert(i) = uicontrol( 'Parent', controlFigH, ...
        'Style', 'check', ...
    	'Units', 'Normalized', ...
    	'Position', [xMin+(i-1)*bw, y(4), bw, bh], ...
        'CallBack', 'mtControlGUI mrkrInvert', ...
        'Value', gv.mrkrInvert(i), ...
        'Max', 1, ...        
        'Min', 0, ...
        'FontWeight', 'b',...
        'FontUnits', 'points', ...
        'FontSize', 8);
    
    h.mrkrSize(i) = uicontrol( 'Parent', controlFigH, ...
        'Style', 'edit', ...
    	'Units', 'Normalized', ...
    	'Position', [xMin+(i-1)*bw, y(5), bw, bh], ...
        'String', gv.mrkrSize(i), ...
        'CallBack', 'mtControlGUI mrkrSize', ...
        'FontWeight', 'b',...
        'FontUnits', 'points', ...
        'FontSize', 8);
    
    h.mrkrSizeX(i) = uicontrol( 'Parent', controlFigH, ...
        'Style', 'edit', ...
    	'Units', 'Normalized', ...
    	'Position', [xMin+(i-1)*bw, y(6), bw, bh], ...
        'String', sprintf('%2.1f', gv.mrkrSizeX(i)), ...
        'CallBack', 'mtControlGUI mrkrSizeX', ...
        'FontWeight', 'b',...
        'FontUnits', 'points', ...
        'FontSize', 8);
    
    h.mrkrSizeTol(i) = uicontrol( 'Parent', controlFigH, ...
        'Style', 'edit', ...
    	'Units', 'Normalized', ...
    	'Position', [xMin+(i-1)*bw, y(7), bw, bh], ...
        'String', sprintf('%2.1f', gv.sizeTol(i)), ...
        'CallBack', 'mtControlGUI mrkrSizeTol', ...
        'FontWeight', 'b',...
        'FontUnits', 'points', ...
        'FontSize', 8);
end

