function mtTrackingConfig;
% mtTrackingConfig;
% by: Doug Weber
% last edit: 3/15/2006
% location: motionTracker toolbox
%
% purpose: this opens a GUI for configuring the motion tracking parameters

global mtConfigH;
global gv;

BUILDGUI = boolean(0);

methods = {'Manual', 'HotSpot', 'matchDot','matchColor'};
methodString = {'Manual', '"Hot-spot"', 'Pattern-matching (Gray)', 'Pattern-matching (Color)'};
tips = {'Manually digitize each marker with mouse', ...
        'Automatically track the brightest pixels (fastest)', ...
        'Match pixel pattern in search box (grayscale images)'...
        'Match pixel pattern in search box (Color images)'};
extrap = {'Linear', 'Polar' };
extrapTips = {'Extrapolate position of each marker independently in X,Y', ...
                'Extrapolate marker position based on polar coordinates relative to adjacent marker'};
            
%Default = do not build the gui, but first need to verify that gui handle
%does not exist or is invalid
BUILDGUI = 0;

if exist('mtConfigH'),
    if isempty( mtConfigH ),
        BUILDGUI = 1;
    else,
        if ~ishandle( mtConfigH.fig ),
            BUILDGUI = 1;
        end
    end
else,
    BUILDGUI = 1;
end

if BUILDGUI,
    mtConfigH = [];
    
    %rebuild GUI
    mtConfigH.fig = figure('Color',[0.8 0.8 0.8], ...
        'MenuBar', 'None', ...
        'Name', 'MT2D Tracking Configurator', ...
        'NumberTitle', 'off', ...
        'Units', 'normalized',...
        'Position', [0.01 0.05 .5 0.15]);
    
    fig = mtConfigH.fig;
    
    xMin = 0.01; xW = 0.3;
    yMin = 0.75; h = 0.15;
    uicontrol( 'Parent', fig, ...
        'Style', 'text', ...
        'Units','Normalized', ...
        'Position',[xMin yMin xW h], ...
        'String', 'Tracking Method', ...
        'FontWeight','b',...
        'FontUnits','points', ...
        'FontSize', 8);
    
    x0 = 0.01; y0 = 0.6; bw = 0.1; bh = 0.15;
    vals = [0 0 1 0]; %default values for "methods" buttons
    for iButton = 1:length(methods),
        mtConfigH.methButns(iButton) = uicontrol( 'Parent', fig, ...
            'Style', 'Radio', ...
            'Units', 'Normalized', ...
            'Position', [x0 y0-(iButton-1)*bh bw bh], ...
            'Max', 1, ...
            'Min', 0, ...
            'Value', vals(iButton), ...
            'Enable', 'On', ...
            'Callback', sprintf('mtControlGui %s', methods{iButton}));
        
        uicontrol( 'Parent', fig, ...
            'Style', 'Text', ...
            'Units', 'Normalized', ...
            'Position', [.1 y0-(iButton-1)*bh 0.25 bh], ...
            'HorizontalAlignment', 'Left', ...
            'String', methodString{iButton}, ...
            'Tooltipstring', tips{iButton});
    end
    
    xMin = 0.4; xW = 0.4;
    yMin = 0.75; h = 0.15;
    uicontrol( 'Parent', fig, ...
        'Style', 'text', ...
        'Units','Normalized', ...
        'Position',[xMin yMin xW h], ...
        'String', 'Extrapolation Method', ...
        'FontWeight','b',...
        'FontUnits','points', ...
        'FontSize', 8);
    
    x0 = 0.4; y0 = 0.6; bw = 0.1; bh = 0.15;
    vals = [1 0];
    for iButton = 1:2,
        mtConfigH.extrapButns(iButton) = uicontrol( 'Parent', fig, ...
            'Style', 'Radio', ...
            'Units', 'Normalized', ...
            'Position', [x0 y0-(iButton-1)*bh bw bh], ...
            'Max', 1, ...
            'Min', 0, ...
            'Value', vals(iButton), ...
            'Enable', 'On', ...
            'Callback', sprintf('mtControlGui %s', extrap{iButton}));
        
        uicontrol( 'Parent', fig, ...
            'Style', 'Text', ...
            'Units', 'Normalized', ...
            'Position', [.5 y0-(iButton-1)*bh 0.25 bh], ...
            'HorizontalAlignment', 'Left', ...
            'String', extrap{iButton}, ...
            'Tooltipstring', extrapTips{iButton});
    end
    mtConfigH.extrapHist = uicontrol( 'Parent', fig, ...
        'Style', 'edit', ...
        'Units', 'Normalized', ...
        'Position', [x0 .25 0.1 0.15], ...
        'String', sprintf('%3.2f', gv.polyPts/ (gv.fps*gv.fpf) ), ...
        'Callback', 'mtControlGui extrapHistory');
    
    uicontrol( 'Parent', fig, ...
        'Style', 'text', ...
        'Units','Normalized', ...
        'Position',[x0+0.1 .25 0.2 0.15], ...
        'String', 'seconds', ...
        'FontWeight','n',...
        'FontUnits','points', ...
        'Tooltipstring', 'length of time to use in extrapolating marker positions', ...
        'FontSize', 8);
    
end

